language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
  
after_success:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar coveralls:report -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=piotrturski-github
